name: Deploy and Invoke Lambda

# Remove the 'on: push' trigger and replace with manual trigger
on:
  workflow_dispatch:  # Allows manual invocation from GitHub UI

jobs:
  deploy-and-invoke:
    # Use your self-hosted runner instead of ubuntu-latest
    runs-on: self-hosted  # Assumes your self-hosted runner is properly labeled and configured
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Match your Lambda runtime

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install junos-eznc boto3 -t .

      # Zip the code for Lambda deployment
      - name: Create deployment package
        run: |
          zip -r lambda_function.zip . -x "*.git*"

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Adjust to your region

      # Check if Lambda exists and create/update accordingly
      - name: Create or Update Lambda Function
        run: |
          # Check if function exists
          if aws lambda get-function --function-name my-route-monitor > /dev/null 2>&1; then
            echo "Function exists, updating..."
            aws lambda update-function-code \
              --function-name my-route-monitor \
              --zip-file fileb://lambda_function.zip
          else
            echo "Function doesn't exist, creating..."
            aws lambda create-function \
              --function-name my-route-monitor \
              --zip-file fileb://lambda_function.zip \
              --handler lambda_function.lambda_handler \
              --runtime python3.9 \
              --role ${{ secrets.LAMBDA_ROLE_RN }} \
              --timeout 300 \
              --memory-size 128
          fi

      # Invoke the Lambda function
      - name: Invoke Lambda
        id: invoke_lambda
        run: |
          aws lambda invoke \
            --function-name my-route-monitor \
            --payload '{}' \
            --log-type Tail \
            response.json > invoke_output.log
          cat response.json

      # Optional: Store invocation output
      - name: Upload invocation result
        uses: actions/upload-artifact@v3
        with:
          name: lambda-response
          path: response.json
